config/routes.rb
Rails.application.routes.draw do
  get 'author/:id' => 'author#show', as: :author

  get 'short_stories' => 'short_story#index'

  get 'short_stories/new' => 'short_story#new', as: :new_story
  get 'short_stories/:id' => 'short_story#show', as: :short_story

  post 'short_stories' => 'short_story#create'

  get 'poems' => 'poem#index'

  get 'poems/new' => 'poem#new', as: :new_poem
  get 'poems/:id' => 'poem#show', as: :poem

  post 'poems' => 'poem#create'

  get 'welcome/index'

  root 'welcome#index'

end

app/models/author.rb
class Author < ActiveRecord::Base

	after_find :auto_tagger

	has_many :poems
	has_many :short_stories
	has_many :taggings, as: :taggable
	has_many :tags, through: :taggings

	validates :name, :biography, presence: true

	def auto_tagger
		# first delete current taggings
		taggings.delete_all
		# save the content into an array content type is biography for author and content for poems/stories
		array_of_content_words = biography.downcase.split(/\W+/)
		# Iterate over all tags and if the array contains one of the tags add that tag to the instances tags
		Tag.all.each {|tag| tags << tag if array_of_content_words.include?(tag.name)}
	end

end

app/models/poem.rb
class Poem < ActiveRecord::Base

	after_find :auto_tagger

	belongs_to :author
	has_many :taggings, as: :taggable
	has_many :tags, through: :taggings

  validates  :author_id, :title, :content, :metaphor, :publish_date, presence: true

  def auto_tagger
		# first delete current taggings
		taggings.delete_all
		# save the content into an array content type is biography for author and content for poems/stories
		array_of_content_words = content.downcase.split(/\W+/)
		# Iterate over all tags and if the array contains one of the tags add that tag to the instances tags
		Tag.all.each {|tag| tags << tag if array_of_content_words.include?(tag.name)}
	end

end

app/models/short_story.rb
class ShortStory < ActiveRecord::Base

	after_find :auto_tagger
	
	belongs_to :author
	has_many :taggings, as: :taggable
	has_many :tags, through: :taggings

  validates  :author_id, :title, :content, :short_description, :publish_date, presence: true

  def auto_tagger
		# first delete current taggings
		taggings.delete_all
		# save the content into an array content type is biography for author and content for poems/stories
		array_of_content_words = content.downcase.split(/\W+/)
		# Iterate over all tags and if the array contains one of the tags add that tag to the instances tags
		Tag.all.each {|tag| tags << tag if array_of_content_words.include?(tag.name)}
	end
	
end

app/models/tag.rb
class Tag < ActiveRecord::Base

	has_many :taggings
	has_many :authors, through: :taggings, source: :taggable, source_type: 'Author'
	has_many :poems, through: :taggings, source: :taggable, source_type: 'Poem'
	has_many :short_stories, through: :taggings, source: :taggable, source_type: 'ShortStory'

	validates :name, presence: true
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
	
	belongs_to :tag 
	belongs_to :taggable, :polymorphic => true 

	validates :tag_id, :taggable_id, :taggable_type, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  def show
  	@author = Author.find(params[:id])
  end
end

app/controllers/poem_controller.rb
class PoemController < ApplicationController
  def index
  	@poems = Poem.all
  end

  def show
  	@poem = Poem.find(params[:id])
  end

  def new
    render 'poem/_new-poem-form'
  end

  def create
  	params = poem_params
  	author = Author.create_with(biography:"This is a happy author that writes classics").find_or_create_by(name: params[:author_id])
  	@poem = Poem.create(title: params[:title], content: params[:content], metaphor: params[:metaphor], publish_date: params[:publish_date], author_id: author.id)
    redirect_to @poem
  end

  private
  def poem_params
    params.require(:poem).permit(:title, :content, :metaphor, :publish_date, :author_id)
  end

end

app/controllers/short_story_controller.rb
class ShortStoryController < ApplicationController
  def index
  	@stories = ShortStory.all
  end

  def show
  	@story = ShortStory.find(params[:id])
  end

  def new
    render 'short_story/_new-story-form'
  end

  def create
  	params = story_params
  	author = Author.create_with(biography:"This is a happy author that writes classics").find_or_create_by(name: params[:author_id])
  	@story = ShortStory.create(title: params[:title], content: params[:content], short_description: params[:short_description], publish_date: params[:publish_date], author_id: author.id)
    redirect_to @story
  end

  private

  def story_params
    params.require(:short_story).permit(:title, :content, :short_description, :publish_date, :author_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@poems = Poem.all
  	@stories = ShortStory.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/poem_helper.rb
module PoemHelper
end

app/helpers/short_story_helper.rb
module ShortStoryHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/author/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
	  <h1><%= @author.name %></h1>
  </div>

  <div class="panel-body">

		<h3>Biography</h3>
		<p><%= @author.biography %></p>
	</div>
	
	<div class="panel-footer">	
		<h3>Tags</h3>
		<% @author.tags.each do |tag| %>
			<span class="label label-default"><%=tag.name.upcase%></span>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Literature Lesson</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Literature Lesson", root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "New Short Story", new_story_path%></li>
        <li><%= link_to "New Poem", new_poem_path%></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Short Stories", short_stories_path%></li>
        <li><%= link_to "Poems", poems_path%></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/poem/_new-poem-form.html.erb
<%= form_for :poem, url: poems_path do |f| %>

<div class="col-md-10">  
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1>Add a new Poem</h1>
    </div>

    <div class="panel-body">
      <p>
      <%= f.label :title  %><br>
      <%= f.text_field :title, :size=>"75", placeholder: "Title", :required => true %>
      </p>

      <p>
        <%= f.label :content %><br>
        <%= f.text_area :content, :size=>"75x15", placeholder: "Content", :required => true %>
      </p>

      <p>
        <%= f.label :metaphor %><br>
        <%= f.text_field :metaphor, :size=>"75", placeholder: "Metaphor", :required => true %>
      </p>

      <p>
        <%= f.label :publish_date %><br>
        <%= f.text_field :publish_date, :size=>"75", placeholder: "DD/MM/YYYY", :required => true %>
      </p>

      <p>
        <%= f.label :author_id, "Author name" %><br>
        <%= f.text_field :author_id, :size=>"75", placeholder: "Author name", :required => true%>
      </p>
    </div>

    <div class="panel-footer">
    <%= f.submit "Submit New Poem", class: 'btn btn-primary' %><br>

    <% end %>

    <%= link_to 'Back', poems_path %>
    </div>
  </div>
</div>

app/views/poem/index.html.erb
<div class="jumbotron">	
	<h2>All the Poems</h2>
	<ul>
		<%@poems.each do |poem|%>
			<li><%= link_to poem.title, poem_path(poem)%></li>
		<%end%>
	</ul>
</div>

app/views/poem/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
	  <h1><%= @poem.title %></h1>
  </div>

  <div class="panel-body">
  	<h3>Description: <%= @poem.metaphor %></h3>

		<h3>Content</h3>
		<p><%= @poem.content %></p>
	</div>
	
	<div class="panel-footer">	
		<h3>Author: <%=link_to @poem.author.name, author_path(@poem.author)%></h3>
		
		<h3>Tags</h3>
		<% @poem.tags.each do |tag| %>
			<span class="label label-primary"><%=tag.name.upcase%></span>
		<% end %>
	</div>
</div>

app/views/short_story/_new-story-form.html.erb
<%= form_for :short_story, url: short_stories_path do |f| %>

<div class="col-md-10">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1>Add a new Short Story</h1>
    </div>

    <div class="panel-body">
      <p>
      <%= f.label :title  %><br>
      <%= f.text_field :title, :size=>"75", placeholder: "Title", :required => true %>
      </p>

      <p>
        <%= f.label :content %><br>
        <%= f.text_area :content, :size=>"75x15", placeholder: "Content", :required => true %>
      </p>

      <p>
        <%= f.label :short_description %><br>
        <%= f.text_field :short_description, :size=>"75", placeholder: "Short description", :required => true %>
      </p>

      <p>
        <%= f.label :publish_date %><br>
        <%= f.text_field :publish_date, :size=>"75", placeholder: "DD/MM/YYYY", :required => true %>
      </p>

      <p>
        <%= f.label :author_id, "Author name" %><br>
        <%= f.text_field :author_id, :size=>"75", placeholder: "Author name", :required => true%>
      </p>
    </div>

    <div class="panel-footer">
    <%= f.submit "Submit New Short Story", class: 'btn btn-primary' %><br>

    <% end %>

    <%= link_to 'Back', short_stories_path %>
    </div>
  </div>
</div>

app/views/short_story/index.html.erb
<div class="jumbotron">
	<h2>All the Short Stories</h2>
		<ul>
			<%@stories.each do |story|%>
				<li><%= link_to story.title, short_story_path(story)%></li>
			<%end%>
		</ul>
</div>

app/views/short_story/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
	  <h1><%= @story.title %></h1>
  </div>

  <div class="panel-body">
  	<h3>Description: <%= @story.short_description %></h3>

		<h3>Content</h3>
		<p><%= @story.content %></p>
	</div>
	
	<div class="panel-footer">	
		<h3>Author: <%=link_to @story.author.name, author_path(@story.author)%></h3>
		
		<h3>Tags</h3>
		<% @story.tags.each do |tag| %>
			<span class="label label-primary"><%=tag.name.upcase%></span>
		<% end %>
	</div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
	<h2>Welcome to Literature Lesson</h2>
	<p>Here you can read all about your favorite authors and their stories and poems. A lot of the content has been tagged fo clarity so that you can decide what content is best for you.</p>
	
	<h3>Stories</h3>
	
	<ul>
		<%@stories.each do |story|%>
			<li><%= link_to story.title, short_story_path(story)%></li>
		<%end%>
	</ul>
	
	<h3>Poems</h3>
	<ul>
		<%@poems.each do |poem|%>
			<li><%= link_to poem.title, poem_path(poem)%></li>
		<%end%>
	</ul>
</div>